src/main/java/com/itwillbs/bookjuk/config/SecurityConfig.java

[24.10.22] 회원가입

---

src/main/java/com/itwillbs/bookjuk/config/SecurityConfig.java
src/main/java/com/itwillbs/bookjuk/controller/join/JoinController.java
src/main/java/com/itwillbs/bookjuk/controller/login/LoginController.java
src/main/java/com/itwillbs/bookjuk/dto/UserDTO.java
src/main/java/com/itwillbs/bookjuk/exception/GlobalExceptionHandler.java
src/main/java/com/itwillbs/bookjuk/exception/ValidationException.java
src/main/java/com/itwillbs/bookjuk/repository/UserRepository.java
src/main/java/com/itwillbs/bookjuk/security/CustomOAuth2User.java
src/main/java/com/itwillbs/bookjuk/security/CustomUserDetails.java
src/main/java/com/itwillbs/bookjuk/security/GoogleResponse.java
src/main/java/com/itwillbs/bookjuk/security/NaverResponse.java
src/main/java/com/itwillbs/bookjuk/security/OAuth2Response.java
src/main/java/com/itwillbs/bookjuk/service/join/JoinService.java
src/main/java/com/itwillbs/bookjuk/service/login/CustomOAuth2UserService.java
src/main/resources/static/js/login/join.js
src/test/java/com/itwillbs/bookjuk/JoinService/JoinTest.java

[24.10.25] 소셜로그인 구현
- 추가로 소셜로그인 회원 userPhone 따로 받아야 하므로 구현중!

[24.10.25] 소셜로그인 구현

---

src/main/java/com/itwillbs/bookjuk/config/SecurityConfig.java

[24.10.25] 개발단계 시큐리티 경로 전체 오픈 설정

[24.10.25] 개발단계 시큐리티 경로 전체 오픈 설정

---

src/main/java/com/itwillbs/bookjuk/entity/BookInfoEntity.java
src/main/resources/templates/fragment/sidebar.html

[24.11.04] 사이드바 링크 수정

---

src/main/java/com/itwillbs/bookjuk/domain/pay/PaymentStatus.java
src/main/java/com/itwillbs/bookjuk/domain/pay/PointPayStatus.java
src/main/java/com/itwillbs/bookjuk/entity/pay/Payment.java
src/main/java/com/itwillbs/bookjuk/entity/pay/PointDeal.java

[2024.11.04 제가인] 엔티티 수정

---

src/main/resources/templates/fragment/header.html
src/main/resources/templates/fragment/sidebar.html

[24.11.06] 헤더, 사이드바 경로 수정

---

src/main/java/com/itwillbs/bookjuk/controller/customer/CutsomerController.java
src/main/java/com/itwillbs/bookjuk/repository/StoreRepository.java
src/main/java/com/itwillbs/bookjuk/service/customer/CustomerService.java
src/main/resources/templates/customer/store.html
src/main/resources/templates/customer/store_info.html
src/main/resources/templates/customer/user.html
src/main/resources/templates/customer/user_info.html

[2024.11.11 손승경] 고객목록 진행중

---

src/main/java/com/itwillbs/bookjuk/service/pay/PaymentService.java
src/main/resources/templates/pay/pay_add.html
src/main/resources/templates/pay/pay_list.html

[2024.11.13 제가인] 오류 수정

---

src/main/java/com/itwillbs/bookjuk/controller/customer/CutsomerController.java
src/main/java/com/itwillbs/bookjuk/entity/StoreEntity.java
src/main/java/com/itwillbs/bookjuk/repository/StoreRepository.java
src/main/java/com/itwillbs/bookjuk/service/customer/CustomerService.java
src/main/resources/static/css/customer/customer.css
src/main/resources/static/js/customer/address.js
src/main/resources/templates/customer/store.html
src/main/resources/templates/customer/store_info.html
src/main/resources/templates/customer/user.html
src/main/resources/templates/customer/user_info.html

[2024.11.13 손승경] 고객탈퇴 진행중

---

src/main/java/com/itwillbs/bookjuk/controller/join/JoinController.java
src/main/java/com/itwillbs/bookjuk/dto/UserDTO.java
src/main/java/com/itwillbs/bookjuk/entity/UserEntity.java
src/main/java/com/itwillbs/bookjuk/service/join/JoinService.java
src/main/resources/static/css/common/mainStyle.css
src/main/resources/static/css/login/joinPhone.css
src/main/resources/static/css/login/style.css
src/main/resources/static/css/user/userInfo.css
src/main/resources/static/js/login/join.js
src/main/resources/static/js/login/validateSMS.js
src/main/resources/templates/login/joinPhone.html
src/main/resources/templates/login/login.html

- 성별 추가 로 받는 기능 생성
- 간편로그인시 생년월일 성별까지 추가로 저장(저장안할시 사용불가)

[24.11.16] 회원가입 페이지 성별 가능추가

---

src/main/java/com/itwillbs/bookjuk/controller/books/BooksController.java
src/main/java/com/itwillbs/bookjuk/dto/BookDTO.java
src/main/java/com/itwillbs/bookjuk/repository/BookInfoRepository.java
src/main/java/com/itwillbs/bookjuk/repository/BooksRepository.java
src/main/java/com/itwillbs/bookjuk/service/books/BooksService.java
src/main/java/com/itwillbs/bookjuk/util/BookConverter.java
src/main/resources/static/css/books/books.css
src/main/resources/static/js/books/bookSearch.js
src/main/resources/templates/books/books.html
src/main/resources/templates/fragment/sidebar.html

[24.11.18 - 은진] 도서검색, 필터 등 페이지네이션 진행중

---

src/main/java/com/itwillbs/bookjuk/config/SecurityConfig.java
src/main/java/com/itwillbs/bookjuk/service/user/UserInfoService.java
src/main/resources/templates/fragment/sidebar.html

[24.11.18] SecurityConfig 설정변경

---

src/main/java/com/itwillbs/bookjuk/controller/customer/CutsomerController.java
src/main/java/com/itwillbs/bookjuk/repository/StoreRepository.java
src/main/resources/templates/customer/store_info.html

[24.11.19]손승경 지점변경 버그 수정

---

src/main/java/com/itwillbs/bookjuk/service/customer/CustomerService.java

[2024.11.19 손승경] 지점수정 버그 수정

---

src/main/resources/templates/books/books.html

[24.11.19 - 은진] 도서등록 최최최종 수정

---

src/main/java/com/itwillbs/bookjuk/controller/pay/PayController.java
src/main/resources/templates/pay/pay_list.html

[2024.11.19 제가인] 페이지네이션 추가

---

src/main/java/com/itwillbs/bookjuk/controller/books/BooksController.java
src/main/resources/templates/books/books.html

[24.11.19] 리스트에 지점이름 추가

---

src/main/java/com/itwillbs/bookjuk/controller/customer/CutsomerController.java

[2024.11.19] 고객목록 정렬수정

---

src/main/java/com/itwillbs/bookjuk/controller/userEvent/UserNotiController.java
src/main/java/com/itwillbs/bookjuk/repository/event/CouponRepository.java
src/main/java/com/itwillbs/bookjuk/repository/event/EventCountRepository.java
src/main/java/com/itwillbs/bookjuk/service/event/EventService.java
src/main/java/com/itwillbs/bookjuk/service/pay/CartService.java
src/main/resources/static/js/event/notification.js
src/main/resources/static/js/event/user_noti.js
src/main/resources/static/js/login/login.js
src/main/resources/static/js/pay/rent.js

결제시 이벤트 조건 확인 구현 및 쿠폰 발행하는 이벤트(신규 가입, 대여)에 알림 수신함의 안읽은 메시지 표시를

---

src/main/java/com/itwillbs/bookjuk/service/pay/PaymentService.java
src/main/resources/templates/pay/pay_add.html
src/main/resources/templates/pay/pay_list.html

[2024.11.20 제가인] 최종 수정
